# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: FabioChelly.csvfab
PackageVersion: 1.14.0
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Commands:
- csvfab
FileExtensions:
- csv
- tsv
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Python.Python.3.12
Installers:
- Architecture: neutral
  InstallerUrl: https://github.com/fabiochelly/csvfab/releases/download/v1.14.0/csvfab-setup-1.14.0.exe
  InstallerSha256: 1A5267FD9A628EF12492BF070347A09214062042030BDF8D257128ED3F628CE2
ManifestType: installer
ManifestVersion: 1.12.0
