# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: FabioChelly.csvfab
PackageVersion: 1.2.1
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Commands:
- csvfab
FileExtensions:
- csv
- tsv
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Python.Python.3.12
Installers:
- Architecture: neutral
  InstallerUrl: https://github.com/fabiochelly/csvfab/releases/download/v1.2.1/csvfab-setup-1.2.1.exe
  InstallerSha256: 1BC39AE94DFA140664B7F4E9096394DE99B3AE9FCEF82CB064265D2BA85FAFB7
ManifestType: installer
ManifestVersion: 1.12.0
