# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: FabioChelly.csvfab
PackageVersion: 1.16.0
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Commands:
- csvfab
FileExtensions:
- csv
- tsv
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Python.Python.3.12
Installers:
- Architecture: neutral
  InstallerUrl: https://github.com/fabiochelly/csvfab/releases/download/v1.16.0/csvfab-setup-1.16.0.exe
  InstallerSha256: 2BC4A78F6B469D5D4790D382667A16106AD99816CE809E896AB65CE57E40C1C2
ManifestType: installer
ManifestVersion: 1.12.0
