# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: FabioChelly.csvfab
PackageVersion: 1.24.0
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Commands:
- csvfab
FileExtensions:
- csv
- tsv
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Python.Python.3.12
Installers:
- Architecture: neutral
  InstallerUrl: https://github.com/fabiochelly/csvfab/releases/download/v1.24.0/csvfab-setup-1.24.0.exe
  InstallerSha256: 409F81CC5E7E6B00E1292857821383C0BED85013C02D73C29D187FA9F4CA95E3
ManifestType: installer
ManifestVersion: 1.12.0
