# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: FabioChelly.csvfab
PackageVersion: 1.20.0
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Commands:
- csvfab
FileExtensions:
- csv
- tsv
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Python.Python.3.12
Installers:
- Architecture: neutral
  InstallerUrl: https://github.com/fabiochelly/csvfab/releases/download/v1.20.0/csvfab-setup-1.20.0.exe
  InstallerSha256: 0D8A8643AED8050E16B777BF201B31AF6F0094A2DE5C1DCC0F7ADE70A240D7C1
ManifestType: installer
ManifestVersion: 1.12.0
