# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: FabioChelly.csvfab
PackageVersion: 1.16.2
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Commands:
- csvfab
FileExtensions:
- csv
- tsv
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Python.Python.3.12
Installers:
- Architecture: neutral
  InstallerUrl: https://github.com/fabiochelly/csvfab/releases/download/v1.16.2/csvfab-setup-1.16.2.exe
  InstallerSha256: 6A0A9B44E6B18F26A6AF1F2FE75FB57A669C17F3A55484D8A875EEFF1B9A37C5
ManifestType: installer
ManifestVersion: 1.12.0
