# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: FabioChelly.csvfab
PackageVersion: 1.25.1
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Commands:
- csvfab
FileExtensions:
- csv
- tsv
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Python.Python.3.12
Installers:
- Architecture: neutral
  InstallerUrl: https://github.com/fabiochelly/csvfab/releases/download/v1.25.1/csvfab-setup-1.25.1.exe
  InstallerSha256: 9B633D3D1FFAAD92DDE729A20D60C3D51ECDC4D3063FF3E0BA9952579655BDBE
ManifestType: installer
ManifestVersion: 1.12.0
